# Generated by Django 5.2.17 on 2026-09-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=150)),
                ('category', models.CharField(default='System', max_length=100)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.CharField(default='127.0.0.1', max_length=50)),
                ('timestamp', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='Success', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('student_count', models.IntegerField(default=0)),
                ('status', models.CharField(default='Active', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('modules', models.IntegerField(default=5)),
                ('prerequisite', models.CharField(blank=True, default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('hod', models.CharField(blank=True, max_length=150, null=True)),
                ('faculty_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('established', models.CharField(blank=True, default='2012', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(default='Midterm', max_length=50)),
                ('start_date', models.CharField(blank=True, max_length=50)),
                ('end_date', models.CharField(blank=True, max_length=50)),
                ('is_locked', models.BooleanField(default=False)),
                ('submitted_papers', models.IntegerField(default=0)),
                ('total_expected', models.IntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(default='General', max_length=50)),
                ('audience', models.CharField(default='All Students & Teachers', max_length=100)),
                ('priority', models.CharField(default='Medium', max_length=30)),
                ('pinned', models.BooleanField(default=False)),
                ('author', models.CharField(default='Administration', max_length=100)),
                ('date', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
