# Generated by Django 5.2.17 on 2026-09-28 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_batch_course_department_examsession_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_no',
            field=models.CharField(blank=True, help_text='University Registration Number (e.g. REG-2022-001)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(blank=True, default='A', help_text='e.g. A, B, C', max_length=20),
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
                ('gpa', models.DecimalField(decimal_places=2, default=3.75, max_digits=3)),
                ('total_credits', models.DecimalField(decimal_places=1, default=15.0, max_digits=4)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
